### ISSUE TITLE
Bananen hergezaubert - you can quickly spawn 2000 bananas

### ISSUE THREAD

**Issue by oltdaniel** [IT4Kids/levels#3]
If you click fast (like a student to break the application) you have a screen of 2000 bananas and the applications runs on 1fps and burns the CPU.

![image](https://user-images.githubusercontent.com/53529846/74099736-0fda6480-4b27-11ea-948c-793ba7ab4044.png)

**Comment by lukas-dachtler** [comment]
fixed in https://github.com/IT4Kids/Cubi/pull/502
